# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-14 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClueNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('unique_id', models.CharField(max_length=7, unique=True)),
                ('text', models.CharField(max_length=140)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prev_node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_node', to='signpost_app.ClueNode')),
            ],
        ),
        migrations.CreateModel(
            name='TreasureHunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasure_hunt', to='signpost_app.ClueNode')),
            ],
        ),
    ]
